spring:
  application:
  name: aiSpring

  ai:
    google:
      genai:
        api-key: ${GCP_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
        embedding:
          api-key: ${GCP_API_KEY}
          text:
            model: text-embedding-004
            dimensions: 768


    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
